---

- name: Include OS-specify variables.
  include_tasks: variables.yml

- name: Include "{{ansible_os_family}}" ssh recipe
  include_tasks: "{{ansible_os_family}}.yaml"

- name: Configure ssh service
  include_tasks: config.yml
  
- name: Include "{{ssh_type_of_node}}" ssh recipe
  include_tasks: "{{ssh_type_of_node}}.yaml"
