---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define base packages.
  set_fact:
    base_packages: "{{ __base_packages }}"
  when: base_packages is not defined