---
- name: Create ssh keys for defined user
  user: name={{ssh_user}} generate_ssh_key=yes shell=/bin/bash groups="{{USER_GROUP}}"

- name: Add the authorized_key to the user '{{ssh_user}}'
  authorized_key: user={{ssh_user}} key="{{ lookup('file', '/tmp/' + ssh_user + '_id_rsa.pub') }}"

- name: Copy the id_rsa.pub file to the user '{{ssh_user}}'
  include: sudo_copy.yaml src=/home/{{ssh_user}}/.ssh/id_rsa.pub dest=/home/{{ssh_user}}/.ssh/id_rsa.pub owner={{ssh_user}} group={{ssh_user}} mode=0644

- name: Copy the id_rsa file to the user
  include: sudo_copy.yaml src=/home/{{ssh_user}}/.ssh/id_rsa dest=/home/{{ssh_user}}/.ssh/id_rsa owner={{ssh_user}} group={{ssh_user}} mode=0600

- name: Update known hosts
  template: src=ssh_known_hosts.conf.j2 dest=/etc/ssh/ssh_known_hosts
